### ISSUE TITLE
Migrating data to existing site

### ISSUE THREAD

**Issue by Jgavin101** [PiwikPRO/plugin-SiteMigration#12]
Using this plugin is it possible to migrate the data to an already existing site? What we want to do is point our tracking code to the new piwik install first and then migrate after so that we do not lose any data. Will this plugin overwrite/affect the existing data on the destination db? Or will it just prepend the visits?

**Comment by mattab** [comment]
Hi there, duplicates https://github.com/PiwikPRO/plugin-SiteMigration/issues/10
