### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by omwbe** [PiwikPRO/plugin-SiteMigration#13]
Hello, I have one installation for site A set to siteid 1.  I have a second installation for site A set to siteid2 (because I have a Site B set to 1).  I changed the sql data for the second installation so that Site A is also set to siteid 1 and Site B is set to sited 3.  So that is clear and we are good to go.

I tried the command ./console migration:site 1 -v

Entered in username: getcert_piwkg
password: (xxxx)
and DB name: getcert_piwkg 
(yes I have the same username and DB name)

However, I keep getting this error:

[Zend_Db_Statement_Mysqli_Exception]
 Mysqli prepare error: Table 'getcert_piwkg.site' doesn't exist

I am not sure what table this is looking for but there is no table with this naming convention.  This is only the DB name.

All tables in this DB are standard Piwik tables with names such as "Piwik_Archive_Blob_2014-10" and "Piwik_Report".

Is there something I am missing?

**Comment by mattab** [comment]
Hi @omwbe 

can you try to add `--db-prefix=piwik_` to the command (to tell Piwik your tables use the `piwik_` prefix?

**Comment by omwbe** [comment]
that seemed to work, however, for some reason not all the table were migrated even though the script ran to completion.  Specifically, all of the archive tables were brought over but none of piwik_log_link_visit_action, piwik_log_visit, and piwik_visit_report.  Also, when the data was migrated it migrated it from siteid 1 to siteid 4 on the 2nd installation.  I ended up changing all 4's to 1's but that it quite cumbersome.  Any thoughts on the missing table data?

**Comment by mattab** [comment]
duplicates https://github.com/PiwikPRO/plugin-SiteMigration/issues/16
