### ISSUE TITLE
Site Migration plugin is way too slow and data isn't migrating under same userID

### ISSUE THREAD

**Issue by shivateja-madipalli** [PiwikPRO/plugin-SiteMigration#29]
I have around 8 sites being tracked on my Piwik in both servers. Server 1 has new data and Server 2 has old data. I need to merge Server 2 with Server 1, I used SiteMigration plugin, some small data were transmitted well but, site data is saved on separate site ID.

Larger data files have not been transmitted at all, it was stuck for more than 7 hours.

I use  Piwik new version.

**Comment by mattab** [comment]
Hi @shivateja-madipalli 
 >Larger data files have not been transmitted at all, it was stuck for more than 7 hours.

Could you maybe copy the output showing where it was stuck? please try with --verbose parameter

**Comment by mattab** [comment]
see https://github.com/PiwikPRO/plugin-SiteMigration/issues/15

**Comment by shivateja-madipalli** [comment]
Hi Matt,

Thanks for replying! 
There was no output, while migrating it takes time to start the process right, It did not output anything.

will try with verbose.

And also I have another issue, where I can use your help.
My issue: 
I have 2 servers running Piwik and tracking 8 sites. Server 1 has new data (After Oct 13th) and Server 2 has old data (Before Oct 13th). 

After SiteMigration plugin, piwik saved old data (from server 2) under siteID 16, where in my server 1 the same website is being tracked under siteID 2, I am trying to merge both data.

How can I do this??

**Comment by mattab** [comment]
See https://github.com/PiwikPRO/plugin-SiteMigration/issues/10

**Comment by shivateja-madipalli** [comment]
Hey Matt,

I guess it should help, not able to work on it as of now.

I am also looking for a contact to speak about Piwik Pro and Piwik Cloud, can you drop me your email.

Thank you.

**Comment by mattab** [comment]
try: http://piwik.pro/contact

**Comment by shivateja-madipalli** [comment]
Thanks *Thumbs Up*

**Comment by shivateja-madipalli** [comment]
Hello Matt,

This is the where it got stuck for a huge db migration.

INFO [2015-10-31 22:15:51] Start transaction
INFO [2015-10-31 22:15:51] Migrating site config
INFO [2015-10-31 22:15:51] Loading existing actions
INFO [2015-10-31 22:15:51] Migrating log data - visits

After this step it was stuck for more than 7 hours

**Comment by mattab** [comment]
When it gets stuck can you execute `SHOW FULL PROCESSLIST` on mysql server and paste here the output showing the SQL that is lagging?

**Comment by shivateja-madipalli** [comment]
Sure! If I restart the process it will take another 10+ hours, give me some time on it.

Secondly Matt,

I have another query too, not related to data migration, totally different.

In my website to retrieve current visitors profile I am using "&method=Live.getVisitorProfile" and while retrieving the data, sometimes I am getting an empty json for first time visitor (a visitor visiting for first time) and if the same visitor visit the page again (refreshing the page) "&method=Live.getVisitorProfile" is retrieving the json value. 

I guess this is because of cookie being saved on client (visitor's) browser.

My implementation is to bring visitor's profile and identify whether it is a first time visitor or returning visitor, accordingly I have to play with my JavaScript.

"var piwikUserDataFile = 'https://xx.xx.xx.xxx/piwik/index.php?module=API&method=Live.getVisitorProfile&visitorId='+visitorId+'&idSite=xx&format=json&token_auth=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';"

new Request.JSONP({url: piwikUserDataFile, callbackKey: 'jsoncallback',log:'true', onComplete: function(data){

}).send();

This is how I am using the Live.getVisitorProfile() and retrieving JSONP value using Mootools Request.JSONP.

Any help on this would be very much appreciated, I am stuck at this since long and thought of going for a PRO for the same as I was not getting any help by post this question on piwik forums and anywhere else.

Please redirect me to right post on this or suggest me an answer.

Thank you!!

**Comment by shivateja-madipalli** [comment]
BTW, after SiteMigration plugin being stopped for merging huge data, I got a message "Invalid Pipe"

**Comment by shivateja-madipalli** [comment]
@mattab After 10+ hours of not showing any update or error, The data migrated. 

I do suggest "showing step by step process of migration" in console will be a good option to understand the process.

I would really appreciate if you can shed some light on the issue with "Request.JSONP".

Thank you.
