### ISSUE TITLE
Save data for later use

### ISSUE THREAD

**Issue by klaxwebmaster** [PiwikPRO/plugin-SiteMigration#9]
Would it be possible to have an option not to write data to a target db but to save as file for later use?

**Comment by mattab** [comment]
Hi @klaxwebmaster 

it is not possible (not the scope / goal of this plugin)

**Comment by mattminuti** [comment]
It seems to me that it is within the scope - servers are often configured to only allow database connections from localhost, so migration to a new server means changing server settings, migrating, then changing them back. Being able to export to file, then copy the file to destination server, then importing, would be nice as a someday feature. :)
